from __future__ import annotations

from dataclasses import asdict
import math
from pathlib import Path
import sys
from typing import Any, Mapping

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from legacy.simcore.models import DynamicsConfig, GeometryConfig, RuntimePaths, SimulationTask, SweepPoint
from legacy.simcore.simulation import MazeBuilder, NavigationSolver, PointSimulator, SimulationTaskRunner

from src.configs.schema import RunConfig, RunResult, infer_flow_condition


def infer_model_variant(*, gamma1_over_gamma0: float, kf: float) -> str:
    if gamma1_over_gamma0 <= 0.0:
        return "no_memory"
    if kf <= 0.0:
        return "no_feedback"
    return "full"


def infer_control_label(model_variant: str, flow_condition: str) -> str:
    if flow_condition == "explicit_no_flow_control":
        return "no_flow"
    labels = {
        "full": "coupled_baseline",
        "no_memory": "no_memory",
        "no_feedback": "no_feedback",
    }
    try:
        return labels[model_variant]
    except KeyError as exc:
        raise ValueError(f"Unsupported model_variant: {model_variant}") from exc


def derive_gamma1_over_gamma0(config: RunConfig) -> float:
    if config.gamma1_over_gamma0 is not None:
        return config.gamma1_over_gamma0
    if config.gamma0 == 0.0:
        return 0.0
    return config.gamma1 / config.gamma0


def _optional_float(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, float) and math.isnan(value):
        return None
    return float(value)


class LegacySimcoreAdapter:
    """Thin wrapper around legacy/simcore that preserves the legacy physics kernel."""

    def __init__(self, project_root: str | Path, runtime_paths: RuntimePaths | None = None) -> None:
        self.project_root = Path(project_root)
        self.runtime_paths = runtime_paths or self._default_runtime_paths(self.project_root)

    @staticmethod
    def _default_runtime_paths(project_root: Path) -> RuntimePaths:
        output_root = project_root / "outputs"
        return RuntimePaths(
            project_root=project_root,
            run_root=output_root / "runs" / "legacy_adapter",
            figure_root=output_root / "figures" / "legacy_adapter",
            table_root=output_root / "summaries" / "legacy_adapter",
        )

    def build_geometry_config(self, config: RunConfig) -> GeometryConfig:
        return GeometryConfig(
            L=float(config.metadata.get("L", 1.0)),
            w=config.wall_thickness,
            g=config.gate_width,
            r_exit=config.exit_radius,
            n_shell=config.n_shell,
            grid_n=config.grid_n,
        )

    def build_dynamics_config(self, config: RunConfig) -> DynamicsConfig:
        return DynamicsConfig(
            gamma0=config.gamma0,
            gamma1_over_gamma0=derive_gamma1_over_gamma0(config),
            Dr=config.Dr,
            v0=config.v0,
            kf=config.kf,
            kBT=config.kBT,
            dt=config.dt,
            Tmax=config.Tmax,
            eps_psi=config.eps_psi,
            bootstrap_resamples=config.bootstrap_resamples,
            n_traj=config.n_traj,
            seed=config.seed,
        )

    def build_sweep_point(
        self,
        config: RunConfig,
        *,
        sweep_id: str | None = None,
        figure_group: str = "adapter_stub",
        control_label: str | None = None,
    ) -> SweepPoint:
        return SweepPoint(
            sweep_id=sweep_id or f"{config.geometry_id}_{config.model_variant}_{config.config_hash[:8]}",
            figure_group=figure_group,
            control_label=control_label or infer_control_label(config.model_variant, config.flow_condition),
            tau_v=config.tau_v,
            tau_f=config.tau_f,
            U=config.U,
            gamma1_over_gamma0=derive_gamma1_over_gamma0(config),
            kf=config.kf,
        )

    def build_simulation_task(
        self,
        config: RunConfig,
        *,
        run_id: str | None = None,
        figure_group: str = "adapter_stub",
    ) -> SimulationTask:
        point = self.build_sweep_point(config, figure_group=figure_group)
        return SimulationTask(
            task_id=f"{config.geometry_id}_{config.model_variant}",
            description="Single-point adapter stub task.",
            mode="adapter_stub",
            run_id=run_id or f"{config.geometry_id}_{config.model_variant}_{config.config_hash[:8]}",
            geometry=self.build_geometry_config(config),
            dynamics=self.build_dynamics_config(config),
            points=(point,),
            detectability_analysis=False,
            notes="Generated by LegacySimcoreAdapter without modifying legacy physics.",
        )

    def run_point(self, config: RunConfig) -> tuple[dict[str, Any], pd.DataFrame, pd.DataFrame]:
        maze = MazeBuilder().build(self.build_geometry_config(config))
        navigation = NavigationSolver().solve(maze)
        simulator = PointSimulator(maze, navigation)
        point = self.build_sweep_point(config)
        dynamics = self.build_dynamics_config(config)
        return simulator.run(point, dynamics, point_seed=config.seed)

    def run_task(self, config: RunConfig, *, overwrite: bool = False) -> Any:
        task = self.build_simulation_task(config)
        runner = SimulationTaskRunner(self.runtime_paths)
        return runner.run(task, overwrite=overwrite)

    def summary_to_result(
        self,
        config: RunConfig,
        summary: Mapping[str, Any],
        *,
        traj_df: pd.DataFrame | None = None,
        trap_df: pd.DataFrame | None = None,
        artifact_paths: Mapping[str, str] | None = None,
        run_id: str | None = None,
    ) -> RunResult:
        finite_exit = pd.Series(dtype=float)
        if traj_df is not None and "t_exit_or_nan" in traj_df:
            finite_exit = traj_df["t_exit_or_nan"].dropna()

        trap_count_mean: float | None = None
        if trap_df is not None and not trap_df.empty:
            counts = trap_df.groupby("traj_id").size()
            trap_count_mean = float(counts.mean())
        elif traj_df is not None:
            trap_count_mean = 0.0

        ci = {
            "p_succ": {"low": summary.get("Psucc_ci_low"), "high": summary.get("Psucc_ci_high")},
            "mfpt": {"low": summary.get("MFPT_ci_low"), "high": summary.get("MFPT_ci_high")},
            "j_proxy": {"low": summary.get("J_proxy_ci_low"), "high": summary.get("J_proxy_ci_high")},
            "sigma_drag": {"low": summary.get("sigma_drag_ci_low"), "high": summary.get("sigma_drag_ci_high")},
            "eta_sigma": {"low": summary.get("eta_sigma_ci_low"), "high": summary.get("eta_sigma_ci_high")},
        }

        return RunResult(
            run_id=run_id or f"{config.geometry_id}_{config.model_variant}_{config.config_hash[:8]}",
            config_hash=config.config_hash,
            geometry_id=config.geometry_id,
            model_variant=config.model_variant,
            flow_condition=config.flow_condition,
            p_succ=float(summary.get("Psucc", 0.0)),
            mfpt_mean=_optional_float(summary.get("MFPT_success_only")),
            mfpt_median=float(finite_exit.median()) if not finite_exit.empty else None,
            mfpt_q90=float(finite_exit.quantile(0.9)) if not finite_exit.empty else None,
            sigma_drag_mean=_optional_float(summary.get("sigma_drag")),
            eta_sigma=_optional_float(summary.get("eta_sigma")),
            trap_time_mean=_optional_float(summary.get("mean_trap_residence")),
            trap_count_mean=trap_count_mean,
            wall_fraction_mean=_optional_float(summary.get("boundary_contact_fraction")),
            revisit_rate_mean=None,
            n_traj=int(summary.get("n_traj", config.n_traj)),
            n_success=int(summary.get("n_success", 0)),
            ci=ci,
            raw_summary_path=artifact_paths.get("summary_csv") if artifact_paths else None,
            metadata={
                "legacy_summary": dict(summary),
                "legacy_artifacts": dict(artifact_paths or {}),
                "input_config": config.to_dict(),
            },
            legacy_model_variant=config.legacy_model_variant,
        )

    def run_config(self, config: RunConfig) -> RunResult:
        summary, traj_df, trap_df = self.run_point(config)
        return self.summary_to_result(config, summary, traj_df=traj_df, trap_df=trap_df)


def legacy_task_point_to_run_config(task: SimulationTask, point: SweepPoint) -> RunConfig:
    gamma0 = task.dynamics.gamma0
    gamma1_over_gamma0 = point.gamma1_over_gamma0
    model_variant = infer_model_variant(
        gamma1_over_gamma0=gamma1_over_gamma0,
        kf=point.kf,
    )
    flow_condition = infer_flow_condition(
        point.U,
        legacy_model_variant=point.control_label if point.control_label == "no_flow" else None,
    )
    legacy_model_variant = "no_flow" if point.control_label == "no_flow" else None
    return RunConfig(
        geometry_id=f"shell_maze_ns{task.geometry.n_shell}_gn{task.geometry.grid_n}",
        model_variant=model_variant,
        flow_condition=flow_condition,
        v0=task.dynamics.v0,
        Dr=task.dynamics.Dr,
        tau_v=point.tau_v,
        gamma0=gamma0,
        gamma1=gamma0 * gamma1_over_gamma0,
        tau_f=point.tau_f,
        U=point.U,
        wall_thickness=task.geometry.w,
        gate_width=task.geometry.g,
        dt=task.dynamics.dt,
        Tmax=task.dynamics.Tmax,
        n_traj=task.dynamics.n_traj,
        seed=task.dynamics.seed,
        exit_radius=task.geometry.r_exit,
        n_shell=task.geometry.n_shell,
        grid_n=task.geometry.grid_n,
        kf=point.kf,
        gamma1_over_gamma0=gamma1_over_gamma0,
        bootstrap_resamples=task.dynamics.bootstrap_resamples,
        kBT=task.dynamics.kBT,
        eps_psi=task.dynamics.eps_psi,
        metadata={
            "legacy_task_id": task.task_id,
            "legacy_run_id": task.run_id,
            "legacy_sweep_id": point.sweep_id,
            "legacy_figure_group": point.figure_group,
            "legacy_control_label": point.control_label,
            "L": task.geometry.L,
            "mode": task.mode,
            "notes": task.notes,
        },
        legacy_model_variant=legacy_model_variant,
    )


def simulation_task_to_dict(task: SimulationTask) -> dict[str, Any]:
    return asdict(task)
